#!/usr/bin/perl

# This script scans your hardware and sends the collected data
# to linux-hardware-guide.com

# Version 0.2

#The Linux-Hardware-Guide library server
$upload_server="http://library.linux-hardware-guide.com";
  
$TMPDIR = "/tmp/LHG.".$$;

print "***********\n";
print "* This is the hardware scan program of \n";
print "* http://www.Linux-Hardware-Guide.com\n";
print "* \n";
print "* It will check your hardware and send the results to \n";
print "* webmaster\@linux-hardware-guide.com\n";
print "* \n";
print "* Log outputs will be stored in: ";
print "$TMPDIR \n";
print "***********\n";
print "\n";
print "\n";


# Harddisk check only possible as root. 
# However, this test (and therefore root privileges) is not mandatory
check_root();

print "Collectin data:\n";

system ("mkdir $TMPDIR");

#System information
print " -> general system information \n";
system ("lsb_release -a > $TMPDIR/lsb_release.txt");
system ("cat /proc/version > $TMPDIR/version.txt");

# General HW overview
print " -> general hardware overview \n";
system ("lsusb > $TMPDIR/lsusb.txt");
system ("lsusb -v > $TMPDIR/lsusb_v.txt 2> $TMPDIR/lsusb_v.err.txt");
system ("lspci -nnk > $TMPDIR/lspci.txt");
system ("cat /proc/cpuinfo > $TMPDIR/cpuinfo.txt");

# system boot messages
print " -> boot messages \n";
system ("dmesg > $TMPDIR/dmesg.txt");

#Scanner search
print " -> checking scanners \n";
system ("scanimage -L > $TMPDIR/scanimage.txt");

#Sound system information
print " -> checking sound system \n";
system ("cat /proc/asound/devices > $TMPDIR/alsa_devices.txt");
system ("cat /proc/asound/cards  > $TMPDIR/alsa_cards.txt");
system ("aplay -l > $TMPDIR/aplay.txt");


# HDD measurement
print " -> checking harddisk\n";
system("dd if=/dev/zero of=/tmp/dd_tempfile bs=1M count=1024 conv=fdatasync,notrunc >  $TMPDIR/dd.txt 2> $TMPDIR/dd.err.txt");
#only possible as root
if ( $< == 0 ) { 
    system ("hdparm -tT /dev/sda > $TMPDIR/hdparm.txt");
    system("hdparm -tT --direct /dev/sda  > $TMPDIR/hdparm_direct.txt");
}else{
    #create empty dummy file
    system ("touch $TMPDIR/hdparm.txt");
    system ("touch $TMPDIR/hdparm_direct.txt");
}
print "done\n";


print "\nUploading data\n";

upload_files();

# Upload request


$mailtext ="Please fill out the following mail body:

1) Hardware to be added to the database: 
(Please enter the hardware name)

2) Hardware URL: 
(Please add a link to the manufacturer's or Amazon's web site where details of the hardware can be found)

3) Describe the Linux compatibility of the Hardware:
(e.g. works out-of-the-box, necessary configuration steps)

4) Please send this mail with its attachments to webmaster\@linux-hardware-guide.com

Thank you for your submission!
";

$files = create_attachment_string();

system ("thunderbird -compose \"to='webmaster\@linux-hardware-guide.com',subject='Linux Hardware - automatic scan',body='$mailtext',attachment='$files'\"");

exit 0;

sub upload_files {
    
  
  my $sid;
  use LWP::UserAgent;  
  use HTTP::Request::Common;
  
  my @allfiles = ("alsa_cards.txt","alsa_devices.txt","aplay.txt","cpuinfo.txt",
                    "dd.err.txt","dd.txt","dmesg.txt","lsb_release.txt","lspci.txt",
                    "lsusb.txt","lsusb_v.err.txt","lsusb_v.txt","scanimage.txt",
                    "version.txt","hdparm.txt","hdparm_direct.txt");
  
  #get session ID
  $request = HTTP::Request->new(GET => $upload_server."/uploadrequest.php?v=0.2");
  $ua = LWP::UserAgent->new;
  $response = $ua->request($request);
  $sid = $response->content;
  
  #$ua = LWP::UserAgent->new;
  #upload files
  $response = $ua->request(POST $upload_server."/uploadfiles.php", 

               Content_Type => 'form-data',
               
               Content      => [ sid     => $sid,
                                file1    => ["$TMPDIR/".$allfiles[0]],
                                file2    => ["$TMPDIR/".$allfiles[1]],
                                file3    => ["$TMPDIR/".$allfiles[2]],
                                file4    => ["$TMPDIR/".$allfiles[3]],
                                file5    => ["$TMPDIR/".$allfiles[4]],
                                file6    => ["$TMPDIR/".$allfiles[5]],
                                file7    => ["$TMPDIR/".$allfiles[6]],
                                file8    => ["$TMPDIR/".$allfiles[7]],
                                file9    => ["$TMPDIR/".$allfiles[8]],
                                file10   => ["$TMPDIR/".$allfiles[9]],
                                file11   => ["$TMPDIR/".$allfiles[10]],
                                file12   => ["$TMPDIR/".$allfiles[11]],
                                file13   => ["$TMPDIR/".$allfiles[12]],
                                file14   => ["$TMPDIR/".$allfiles[13]],
                                file15   => ["$TMPDIR/".$allfiles[14]],
                                file16   => ["$TMPDIR/".$allfiles[15]],
                               ]
               
               );
  
  print " -> "; 
  print $response->content;
  
  print "\n\nSee your scan results at:\nhttp://www.linux-hardware-guide.com/hardware-profile/scan-".$sid."\n";

  exit 0;
  
}

  
sub check_root {
    
    if ( $< != 0 ) {
        print "WARNING:\n";
        print "========\n";
        print "This script is running without root priveleges.\n";
        print "Harddisk performance can only be measured with root priveleges and therefore will be skipped.\n";
        print "\n";
        print "\n";
    }
}

sub create_attachment_string {
    my @allfiles = ("alsa_cards.txt","alsa_devices.txt","aplay.txt","cpuinfo.txt",
                    "dd.err.txt","dd.txt","dmesg.txt","lsb_release.txt","lspci.txt",
                    "lsusb.txt","lsusb_v.err.txt","lsusb_v.txt","scanimage.txt",
                    "version.txt","hdparm.txt","hdparm_direct.txt");
    
    foreach (@allfiles) {
        if (-e "$TMPDIR/$_") {
            $attachments .= "$TMPDIR/$_,";
        }
    }
    
    $attachments = substr($attachments,0,-1);
    return $attachments;
    
}

