#!/usr/bin/perl

# This script scans your hardware and sends the collected data
# to linux-hardware-guide.com

$VERSION = "0.3.2";

$DEBUG = 0;

# The Linux-Hardware-Guide library server
$upload_server="http://library.linux-hardware-guide.com";
  
$TMPDIR = "/tmp/LHG.".$$;

print "***********\n";
print "* This is the hardware scan program of \n";
print "* http://www.Linux-Hardware-Guide.com\n";
print "* \n";
print "* It will check your hardware and send the results to \n";
print "* webmaster\@linux-hardware-guide.com\n";
print "* \n";
print "* Log outputs will be stored in: ";
print "$TMPDIR \n";
print "***********\n";
print "\n";
print "\n";

my @allfiles = ("alsa_cards.txt","alsa_devices.txt","aplay.txt","cpuinfo.txt",
                    "dd.err.txt","dd.txt","dmesg.txt","lsb_release.txt","lspci.txt",
                    "lsusb.txt","lsusb_v.err.txt","lsusb_v.txt","scanimage.txt",
                    "version.txt","hdparm.txt","hdparm_direct.txt");

# Harddisk check only possible as root. 
# However, this test (and therefore root privileges) is not mandatory
check_root();

print "Collectin data:\n";

system ("mkdir $TMPDIR");

# System information
print " -> general system information \n";
system ("lsb_release -a > $TMPDIR/lsb_release.txt");
system ("cat /proc/version > $TMPDIR/version.txt");

# General HW overview
print " -> general hardware overview \n";
system ("lsusb > $TMPDIR/lsusb.txt");
system ("lsusb -v > $TMPDIR/lsusb_v.txt 2> $TMPDIR/lsusb_v.err.txt");
system ("lspci -nnk > $TMPDIR/lspci.txt");
system ("cat /proc/cpuinfo > $TMPDIR/cpuinfo.txt");

# system boot messages
print " -> boot messages \n";
system ("dmesg > $TMPDIR/dmesg.txt");

# system boot messages
print " -> graphic card/drivers \n";
check_graphics();

# Scanner search
print " -> checking scanners \n";
system ("scanimage -L > $TMPDIR/scanimage.txt");

# Sound system information
print " -> checking sound system \n";
system ("cat /proc/asound/devices > $TMPDIR/alsa_devices.txt");
system ("cat /proc/asound/cards  > $TMPDIR/alsa_cards.txt");
system ("aplay -l > $TMPDIR/aplay.txt");


# HDD measurement
print " -> checking harddisk\n";
check_drives();
system("dd if=/dev/zero of=/tmp/dd_tempfile bs=1M count=1024 conv=fdatasync,notrunc >  $TMPDIR/dd.txt 2> $TMPDIR/dd.err.txt");
#only possible as root
if ( $< == 0 ) { 
    system ("hdparm -tT /dev/sda > $TMPDIR/hdparm.txt");
    system("hdparm -tT --direct /dev/sda  > $TMPDIR/hdparm_direct.txt");
}else{
    #create empty dummy file
    system ("touch $TMPDIR/hdparm.txt");
    system ("touch $TMPDIR/hdparm_direct.txt");
}

# Equipment paired with Logitech Unifying Receivers is hard to distinguish
# We will need some help by other tools here
print " -> checking Unifying Receivers \n";
check_unifying_receivers();

misc_stats();

print " -> Make data anonymous\n";
anonymize_data();

print "done\n";

print "\nUploading data\n";

#DEBUG MODE
#exit 0;
#

if ($DEBUG == 0) {
    # Upload request
    upload_files();
    exit 0;
} else {
    exit 0;
}    


$mailtext ="Please fill out the following mail body:

1) Hardware to be added to the database: 
(Please enter the hardware name)

2) Hardware URL: 
(Please add a link to the manufacturer's or Amazon's web site where details of the hardware can be found)

3) Describe the Linux compatibility of the Hardware:
(e.g. works out-of-the-box, necessary configuration steps)

4) Please send this mail with its attachments to webmaster\@linux-hardware-guide.com

Thank you for your submission!
";

$files = create_attachment_string();

system ("thunderbird -compose \"to='webmaster\@linux-hardware-guide.com',subject='Linux Hardware - automatic scan',body='$mailtext',attachment='$files'\"");

exit 0;

sub upload_files {
    
  
  my $sid;
  use LWP::UserAgent;  
  use HTTP::Request::Common;
  
  #get session ID
  $request = HTTP::Request->new(GET => $upload_server."/uploadrequest.php?v=0.2");
  $ua = LWP::UserAgent->new;
  $response = $ua->request($request);
  $sid = $response->content;
  
  #$ua = LWP::UserAgent->new;
  #upload files
  $response = $ua->request(POST $upload_server."/uploadfiles.php", 

               Content_Type => 'form-data',
               
               Content      => [ sid     => $sid,
                                file1    => ["$TMPDIR/".$allfiles[0]],
                                file2    => ["$TMPDIR/".$allfiles[1]],
                                file3    => ["$TMPDIR/".$allfiles[2]],
                                file4    => ["$TMPDIR/".$allfiles[3]],
                                file5    => ["$TMPDIR/".$allfiles[4]],
                                file6    => ["$TMPDIR/".$allfiles[5]],
                                file7    => ["$TMPDIR/".$allfiles[6]],
                                file8    => ["$TMPDIR/".$allfiles[7]],
                                file9    => ["$TMPDIR/".$allfiles[8]],
                                file10   => ["$TMPDIR/".$allfiles[9]],
                                file11   => ["$TMPDIR/".$allfiles[10]],
                                file12   => ["$TMPDIR/".$allfiles[11]],
                                file13   => ["$TMPDIR/".$allfiles[12]],
                                file14   => ["$TMPDIR/".$allfiles[13]],
                                file15   => ["$TMPDIR/".$allfiles[14]],
                                file16   => ["$TMPDIR/".$allfiles[15]],
                               ]
               
               );
  
  print " -> "; 
  print $response->content;
  
  print "\n\nSee your scan results at:\nhttp://www.linux-hardware-guide.com/hardware-profile/scan-".$sid."\n";

  exit 0;
  
}

  
sub check_root {
    
    if ( $< != 0 ) {
        #print "WARNING:\n";
        #print "========\n";
        print "(This script is running without root privileges. ";
        print "Harddisk performance can only be measured with root priveleges and therefore will be skipped.)\n";
        #print "\n";
        print "\n";
    }
}

sub create_attachment_string {
    
    foreach (@allfiles) {
        if (-e "$TMPDIR/$_") {
            $attachments .= "$TMPDIR/$_,";
        }
    }
    
    $attachments = substr($attachments,0,-1);
    return $attachments;
    
}

sub anonymize_data {
    
    # We do not need IP or MAC addresses, therefore we filter them before uploading the files.
    # Serial Numbers of Equipment on the other hand might carry important 
    # information, e.g. if hardware compatibility changes for certain serial numbers
    # Therefore, serial numbers are currently not filtered
    
    foreach (@allfiles) {
        if (-e "$TMPDIR/$_") {
            
            #remove MAC addresses
            system('sed -i "s/([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})/00:11:22:33:44:55/g" '.$TMPDIR."/".$_);
            
            #remove IP addresses
            system('sed -i "s/\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b/192.168.0.0/g" '.$TMPDIR."/".$_);

        }
    }
    
    return $attachments;
    
}

sub check_unifying_receivers {
    #ToDo: This information should be stored in a separate file
    
    $path_solaar = `which solaar-cli`;
    if ($path_solaar eq "") {
        # tool not installed
    } else {
        
        system( 'echo "\n ------ solaar-cli output ------- \n" >> '.$TMPDIR.'/dmesg.txt');
        $cmd = substr($path_solaar,0,-1). " show >> $TMPDIR/dmesg.txt 2>> $TMPDIR/dmesg.txt ";
        system($cmd);
    
    }
}

sub check_graphics {
    #ToDo: This information should be stored in a separate file
    
    $path_xinput = `which xinput`;
    if ($path_solaar eq "") {
        # tool not installed
    } else {
        system( 'echo "\n ------ xinput ------- \n" >> '.$TMPDIR.'/dmesg.txt');
        $cmd = substr($path_xinput,0,-1). " >> $TMPDIR/dmesg.txt 2>> $TMPDIR/dmesg.txt ";
        system($cmd);
    }
    
    system( 'echo "\n ------ Xorg.log ------- \n" >> '.$TMPDIR.'/dmesg.txt');
    $cmd = "cat /var/log/Xorg.0.log >> $TMPDIR/dmesg.txt 2>> $TMPDIR/dmesg.txt ";
    system($cmd);

}

sub check_drives {
    #ToDo: This information should be stored in a separate file
    
    if (-e "/sys/block/") {
        system( 'echo "\n ------ ls -d /sys/block/s* ------- \n" >> '.$TMPDIR.'/dmesg.txt');
        $cmd0 = "ls -d /sys/block/s* >> $TMPDIR/dmesg.txt 2>> $TMPDIR/dmesg.txt ";
        system( 'echo "\n ------ /sys/block/s*/device/model ------- \n" >> '.$TMPDIR.'/dmesg.txt');
        $cmd1 = "cat /sys/block/s*/device/model >> $TMPDIR/dmesg.txt 2>> $TMPDIR/dmesg.txt ";
        system($cmd0);
        system($cmd1);
    }
    
}


sub misc_stats {
    
    # Adding some anonymous stats 
    
    system( 'echo "\n ------ STATS ------- \n" >> '.$TMPDIR.'/version.txt');
    system( 'echo "LHG_VERSION = '.$VERSION.' \n" >> '.$TMPDIR.'/version.txt');

}
